# Generated by Django 4.1.7 on 2023-04-14 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_category_product_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='brand',
            new_name='category',
        ),
    ]
